FROM dunglas/frankenphp:php8.3-alpine

WORKDIR /app

COPY . /app

RUN docker-php-ext-install mysqli pdo pdo_mysql

ENV SERVER_NAME=:80

CMD ["sh", "-c", "frankenphp php-server --listen :${PORT:-80} --root /app"]